STOPWORDS = set(
    [
        # PRONOUNS
        "i",
        "me",
        "my",
        "myself",
        "we",
        "our",
        "ours",
        "ourselves",
        "you",
        "your",
        "yours",
        "yourself",
        "yourselves",
        "he",
        "him",
        "his",
        "himself",
        "she",
        "her",
        "hers",
        "herself",
        "it",
        "its",
        "itself",
        "they",
        "them",
        "their",
        "theirs",
        "themselves",
        "what",
        "which",
        "who",
        "whom",
        "this",
        "that",
        "these",
        "those",
        # AUXILIARIES
        "am",
        "is",
        "are",
        "was",
        "were",
        "be",
        "been",
        "being",
        "have",
        "has",
        "had",
        "having",
        "do",
        "does",
        "did",
        "doing",
        # ARTICLES
        "a",
        "an",
        "the",
        # COORDINATIONS
        # "and",
        # "but",
        # "if",
        # "or",
        # "because",
        # "as",
        # "until",
        # "while",
        # "of",
        # "at",
        # "by",
        # "for",
        # "with",
        # "about",
        # "against",
        # "between",
        # "into",
        # "through",
        # "during",
        # "before",
        # "after",
        # "above",
        # "below",
        # "to",
        # "from",
        # "up",
        # "down",
        # "in",
        # "out",
        # "on",
        # "off",
        # "over",
        # "under",
        # "again",
        # "further",
        # "then",
        # "once",
        # "here",
        # "there",
        # "when",
        # "where",
        # "why",
        # "how",
        # QUANTITIES
        # "all",
        # "any",
        # "both",
        # "each",
        # "few",
        # "more",
        # "most",
        # "other",
        # "some",
        # "such",
        # NEGATIONS
        # "no",
        # "nor",
        # "not",
        # "only",
        # "own",
        # "same",
        # "so",
        # "than",
        # "too",
        # "very",
        # "s",
        # "t",
        # "can",
        # "will",
        # "just",
        # "don",
        # "should",
        # "now",
    ]
)
